services:
  monkeytype-frontend:
    container_name: monkeytype-frontend
    image: node:gallium-bullseye
    restart: on-failure
    ports:
      - "3010:3010"
    volumes:
      - ../:/monkeytype
    user: node
    entrypoint: 'bash -c "cd /monkeytype && npm run dev-fe"'
